version: "3.8"

services:
  piston:
    image: ghcr.io/engineer-man/piston:latest
    container_name: codeguru-piston

    privileged: true

    restart: unless-stopped

    ports:
      - "2000:2000"